AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  FavoritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Favorites
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: playerId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: playerId
          KeyType: RANGE

  GetTeamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ../backend/getTeams
      Environment:
        Variables:
          API_KEY: 4cd9312d-df03-406c-92d0-fbad477cc8d8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /teams
            Method: get

  GetPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ../backend/getPlayers
      Environment:
        Variables:
          API_KEY: 4cd9312d-df03-406c-92d0-fbad477cc8d8
      Events:
        Api:
          Type: Api
          Properties:
            Path: /players
            Method: get

  SaveFavoriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ../backend/saveFavorite
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Favorites
      Environment:
        Variables:
          TABLE: Favorites
      Events:
        Api:
          Type: Api
          Properties:
            Path: /favorite
            Method: post

  GetFavoritesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: ../backend/getFavorites
      Policies:
        - DynamoDBReadPolicy:
            TableName: Favorites
      Environment:
        Variables:
          TABLE: Favorites
      Events:
        Api:
          Type: Api
          Properties:
            Path: /favorites
            Method: get