AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BallDontLieApiKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  FavoritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Favorites
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: playerId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: playerId
          KeyType: RANGE

  GetTeamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../backend/getTeams
      Environment:
        Variables:
          API_KEY: !Ref BallDontLieApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /teams
            Method: ANY

  GetPlayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../backend/getPlayers
      Environment:
        Variables:
          API_KEY: !Ref BallDontLieApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /players
            Method: ANY

  SaveFavoriteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../backend/saveFavorite
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FavoritesTable
      Environment:
        Variables:
          TABLE: !Ref FavoritesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /favorite
            Method: post

  GetFavoritesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ../backend/getFavorites
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FavoritesTable
      Environment:
        Variables:
          TABLE: !Ref FavoritesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /favorites
            Method: ANY

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"